=pod

=head1 Rex::Template::TT - Use Template::Toolkit with Rex

This module enables the use of Template::Toolkit for Rex Templates.

=head1 USAGE

Just include the file into your I<Rexfile>.

 # Rexfile
 use Rex::Template::TT;
    
 task prepare => sub {
    
    file "/a/file/on/the/remote/machine.conf",
       content => template("path/to/your/template.tt", 
                              var1  => $var1,
                              arr1  => \@arr1,
                              hash1 => \%hash1,
                          );
                       
 };

